# Generated by Django 3.2.3 on 2021-05-26 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaname', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyname', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Dprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=400)),
                ('middlename', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('Homeowner', models.CharField(max_length=150)),
                ('relationtoHomeowner', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=150)),
                ('mothername', models.CharField(max_length=100)),
                ('motherfamilyname', models.CharField(max_length=100)),
                ('dateofbirth', models.DateField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('TRANS', 'Trans Gender')], max_length=20)),
                ('education', models.CharField(blank=True, max_length=2000, null=True)),
                ('educationcertification', models.TextField(blank=True, null=True)),
                ('educationislamic', models.CharField(blank=True, max_length=1000, null=True)),
                ('skill', models.TextField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('pravasi', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=2000, null=True)),
                ('contactno', models.CharField(max_length=100)),
                ('bloodgroup', models.CharField(blank=True, choices=[('A +ve', 'A +ve'), ('B +ve', 'B +ve'), ('AB +ve', 'AB +ve'), ('A -ve', 'A -ve'), ('B -ve', 'B -ve'), ('AB -ve', 'AB -ve'), ('O +ve', 'O +ve'), ('O -ve', 'O -ve'), ('Other', 'Other')], max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('martialstatus', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=25)),
                ('spousedetails', models.CharField(blank=True, max_length=300, null=True)),
                ('spouseoccupation', models.CharField(blank=True, max_length=300, null=True)),
                ('noofkids', models.IntegerField(blank=True, null=True)),
                ('disablities', models.TextField(blank=True, null=True)),
                ('previousmahallu', models.CharField(blank=True, max_length=100, null=True)),
                ('alive', models.BooleanField(blank=True, null=True)),
                ('dateofdeath', models.DateField(blank=True, null=True)),
                ('deathreason', models.TextField(blank=True, null=True)),
                ('covidvaccine', models.CharField(blank=True, max_length=300, null=True)),
                ('otherdetails', models.TextField(blank=True, null=True)),
                ('userid', models.IntegerField()),
                ('lastmodifieduserid', models.IntegerField()),
                ('registrationdate', models.DateField()),
                ('lastmodifieddate', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataprofile.area')),
                ('familyname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataprofile.family')),
            ],
        ),
    ]
